import os
import psycopg2
from psycopg2.extras import RealDictCursor
from psycopg2 import IntegrityError
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set in .env")


def get_db_connection():
    return psycopg2.connect(
        DATABASE_URL,
        cursor_factory=RealDictCursor
    )


def init_db():
    conn = get_db_connection()
    cursor = conn.cursor()

    # 1. Create Bikes Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS bikes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT UNIQUE NOT NULL,
            base_mileage REAL NOT NULL,
            tank_capacity REAL NOT NULL DEFAULT 10.0
        )
    """)

    # 2. Create Trips Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS trips (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            start_location TEXT,
            end_location TEXT,
            bike_name TEXT,
            speed REAL,
            fuel_input REAL,
            road_type TEXT,
            load_type TEXT,
            predicted_mileage REAL,
            predicted_range REAL,
            distance_km REAL,
            duration_hours REAL,
            status TEXT,
            fuel_needed REAL
        )
    """)

    # 3. Create Refueling Logs Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS refuel_logs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            date TEXT NOT NULL,
            liters REAL NOT NULL,
            price_per_liter REAL NOT NULL,
            cost REAL NOT NULL,
            odometer REAL NOT NULL,
            notes TEXT
        )
    """)

    # 4. Create Users Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            phone TEXT UNIQUE NOT NULL,
            name TEXT NOT NULL,
            bike_name TEXT DEFAULT 'Hero Splendor',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # 5. Create Group Rides Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS group_rides (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT UNIQUE NOT NULL,
            name TEXT NOT NULL,
            created_by TEXT NOT NULL,
            status TEXT DEFAULT 'ACTIVE',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # 6. Create Group Riders Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS group_riders (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id INTEGER NOT NULL,
            rider_id TEXT NOT NULL,
            rider_label TEXT NOT NULL,
            rider_name TEXT NOT NULL,
            bike_name TEXT NOT NULL,
            lat REAL NOT NULL,
            lon REAL NOT NULL,
            fuel REAL NOT NULL,
            fuel_range REAL NOT NULL,
            mileage REAL NOT NULL,
            speed REAL NOT NULL,
            status TEXT NOT NULL DEFAULT 'Cruising',
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(group_id, rider_id),
            FOREIGN KEY (group_id)
                REFERENCES group_rides(id)
                ON DELETE CASCADE
        )
    """)

    # Prepopulate default bikes if table is empty
    cursor.execute("SELECT COUNT(*) FROM bikes")
    if cursor.fetchone()["count"] == 0:
        default_bikes = [
            ("Hero Splendor", 60.0, 9.8),
            ("Honda Shine", 55.0, 10.5),
            ("Bajaj Pulsar 150", 45.0, 15.0),
            ("TVS Apache", 40.0, 12.0)
        ]

        cursor.executemany(
            """
            INSERT INTO bikes (name, base_mileage, tank_capacity)
            VALUES (%s, %s, %s)
            ON CONFLICT (name) DO NOTHING
            """,
            default_bikes
        )

    conn.commit()
    cursor.close()
    conn.close()


# ============================================================================
# BIKE HELPERS
# ============================================================================

def get_all_bikes():
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute("SELECT * FROM bikes ORDER BY name ASC")
    bikes = cursor.fetchall()

    cursor.close()
    conn.close()

    return [dict(b) for b in bikes]


def add_bike(name, base_mileage, tank_capacity):
    conn = get_db_connection()
    cursor = conn.cursor()

    try:
        cursor.execute(
            """
            INSERT INTO bikes (name, base_mileage, tank_capacity)
            VALUES (%s, %s, %s)
            """,
            (name, base_mileage, tank_capacity)
        )

        conn.commit()
        success = True

    except IntegrityError:
        conn.rollback()
        success = False

    finally:
        cursor.close()
        conn.close()

    return success


def delete_bike(bike_id):
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "DELETE FROM bikes WHERE id = %s",
        (bike_id,)
    )

    conn.commit()
    cursor.close()
    conn.close()


# ============================================================================
# TRIP HELPERS
# ============================================================================

def get_all_trips():
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "SELECT * FROM trips ORDER BY timestamp DESC"
    )

    trips = cursor.fetchall()

    cursor.close()
    conn.close()

    return [dict(t) for t in trips]


def add_trip(
    start_location,
    end_location,
    bike_name,
    speed,
    fuel_input,
    road_type,
    load_type,
    predicted_mileage,
    predicted_range,
    distance_km,
    duration_hours,
    status,
    fuel_needed
):
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        INSERT INTO trips (
            start_location,
            end_location,
            bike_name,
            speed,
            fuel_input,
            road_type,
            load_type,
            predicted_mileage,
            predicted_range,
            distance_km,
            duration_hours,
            status,
            fuel_needed
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
        (
            start_location,
            end_location,
            bike_name,
            speed,
            fuel_input,
            road_type,
            load_type,
            predicted_mileage,
            predicted_range,
            distance_km,
            duration_hours,
            status,
            fuel_needed
        )
    )

    conn.commit()
    cursor.close()
    conn.close()


def delete_trip(trip_id):
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "DELETE FROM trips WHERE id = %s",
        (trip_id,)
    )

    conn.commit()
    cursor.close()
    conn.close()


# ============================================================================
# REFUEL HELPERS
# ============================================================================

def get_all_refuels():
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "SELECT * FROM refuel_logs ORDER BY date DESC, id DESC"
    )

    refuels = cursor.fetchall()

    cursor.close()
    conn.close()

    return [dict(r) for r in refuels]


def add_refuel(
    date,
    liters,
    price_per_liter,
    cost,
    odometer,
    notes
):
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        INSERT INTO refuel_logs (
            date,
            liters,
            price_per_liter,
            cost,
            odometer,
            notes
        )
        VALUES (%s, %s, %s, %s, %s, %s)
        """,
        (
            date,
            liters,
            price_per_liter,
            cost,
            odometer,
            notes
        )
    )

    conn.commit()
    cursor.close()
    conn.close()


def delete_refuel(refuel_id):
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "DELETE FROM refuel_logs WHERE id = %s",
        (refuel_id,)
    )

    conn.commit()
    cursor.close()
    conn.close()


# ============================================================================
# STATISTICS
# ============================================================================

def get_stats():
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute("SELECT COUNT(*) AS count FROM trips")
    total_trips = cursor.fetchone()["count"]

    cursor.execute("SELECT SUM(distance_km) AS total FROM trips")
    total_dist = cursor.fetchone()["total"] or 0.0

    cursor.execute("SELECT COUNT(*) AS count FROM refuel_logs")
    total_refuels = cursor.fetchone()["count"]

    cursor.execute("SELECT SUM(cost) AS total FROM refuel_logs")
    total_spend = cursor.fetchone()["total"] or 0.0

    cursor.execute("SELECT SUM(liters) AS total FROM refuel_logs")
    total_liters = cursor.fetchone()["total"] or 0.0

    cursor.execute("SELECT COUNT(*) AS count FROM bikes")
    total_bikes = cursor.fetchone()["count"]

    cursor.close()
    conn.close()

    return {
        "total_trips": total_trips,
        "total_distance_km": round(float(total_dist), 2),
        "total_refuels": total_refuels,
        "total_spend": round(float(total_spend), 2),
        "total_liters": round(float(total_liters), 2),
        "total_bikes": total_bikes
    }


# ============================================================================
# USER AUTHENTICATION HELPERS
# ============================================================================

def get_or_create_user(phone, name=None, bike_name="Hero Splendor"):
    phone = str(phone).strip()

    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "SELECT * FROM users WHERE phone = %s",
        (phone,)
    )

    user = cursor.fetchone()

    if user:
        if name and name.strip() and user["name"] != name.strip():

            cursor.execute(
                """
                UPDATE users
                SET name = %s, bike_name = %s
                WHERE phone = %s
                """,
                (
                    name.strip(),
                    bike_name or user["bike_name"],
                    phone
                )
            )

            conn.commit()

            cursor.execute(
                "SELECT * FROM users WHERE phone = %s",
                (phone,)
            )

            user = cursor.fetchone()

        cursor.close()
        conn.close()

        return dict(user)

    user_name = (
        name.strip()
        if name and name.strip()
        else f"Rider {phone[-4:]}"
    )

    cursor.execute(
        """
        INSERT INTO users (phone, name, bike_name)
        VALUES (%s, %s, %s)
        """,
        (
            phone,
            user_name,
            bike_name or "Hero Splendor"
        )
    )

    conn.commit()

    cursor.execute(
        "SELECT * FROM users WHERE phone = %s",
        (phone,)
    )

    user = cursor.fetchone()

    cursor.close()
    conn.close()

    return dict(user)


def get_user_by_phone(phone):
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "SELECT * FROM users WHERE phone = %s",
        (str(phone).strip(),)
    )

    user = cursor.fetchone()

    cursor.close()
    conn.close()

    return dict(user) if user else None


def update_user_profile(phone, name, bike_name):
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        """
        UPDATE users
        SET name = %s, bike_name = %s
        WHERE phone = %s
        """,
        (
            name.strip(),
            bike_name,
            str(phone).strip()
        )
    )

    conn.commit()

    cursor.execute(
        "SELECT * FROM users WHERE phone = %s",
        (str(phone).strip(),)
    )

    user = cursor.fetchone()

    cursor.close()
    conn.close()

    return dict(user) if user else None


# ============================================================================
# GROUP RIDE HELPERS
# ============================================================================

RIDER_LABELS = [
    "Rider A",
    "Rider B",
    "Rider C",
    "Rider D",
    "Rider E",
    "Rider F",
    "Rider G",
    "Rider H"
]


def create_group_ride(code, name, created_by):
    code = code.strip().upper()

    conn = get_db_connection()
    cursor = conn.cursor()

    try:
        cursor.execute(
            """
            INSERT INTO group_rides (code, name, created_by)
            VALUES (%s, %s, %s)
            """,
            (
                code,
                name.strip(),
                str(created_by).strip()
            )
        )

        conn.commit()

        cursor.execute(
            "SELECT * FROM group_rides WHERE code = %s",
            (code,)
        )

        ride = cursor.fetchone()

        cursor.close()
        conn.close()

        return dict(ride) if ride else None

    except IntegrityError:
        conn.rollback()
        cursor.close()
        conn.close()

        return None


def get_group_ride_by_code(code):
    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "SELECT * FROM group_rides WHERE code = %s",
        (code.strip().upper(),)
    )

    ride = cursor.fetchone()

    cursor.close()
    conn.close()

    return dict(ride) if ride else None


def join_group_ride(
    code,
    rider_id,
    rider_name,
    bike_name,
    lat,
    lon,
    fuel=2.5,
    speed=50.0,
    fuel_range=120.0,
    mileage=50.0,
    status="Cruising"
):
    code = code.strip().upper()

    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "SELECT * FROM group_rides WHERE code = %s",
        (code,)
    )

    ride = cursor.fetchone()

    if not ride:
        cursor.close()
        conn.close()

        return None, "Group ride not found"

    group_id = ride["id"]

    cursor.execute(
        """
        SELECT *
        FROM group_riders
        WHERE group_id = %s AND rider_id = %s
        """,
        (
            group_id,
            str(rider_id)
        )
    )

    existing = cursor.fetchone()

    if existing:
        label = existing["rider_label"]

        cursor.execute(
            """
            UPDATE group_riders
            SET rider_name = %s,
                bike_name = %s,
                lat = %s,
                lon = %s,
                fuel = %s,
                speed = %s,
                fuel_range = %s,
                mileage = %s,
                status = %s,
                updated_at = CURRENT_TIMESTAMP
            WHERE id = %s
            """,
            (
                rider_name,
                bike_name,
                lat,
                lon,
                fuel,
                speed,
                fuel_range,
                mileage,
                status,
                existing["id"]
            )
        )

        conn.commit()

        cursor.execute(
            "SELECT * FROM group_riders WHERE id = %s",
            (existing["id"],)
        )

        updated = cursor.fetchone()

        cursor.close()
        conn.close()

        return dict(updated), None

    cursor.execute(
        """
        SELECT rider_label
        FROM group_riders
        WHERE group_id = %s
        ORDER BY id ASC
        """,
        (group_id,)
    )

    current_riders = cursor.fetchall()

    used_labels = {
        r["rider_label"]
        for r in current_riders
    }

    assigned_label = None

    for lbl in RIDER_LABELS:
        if lbl not in used_labels:
            assigned_label = lbl
            break

    if not assigned_label:
        assigned_label = f"Rider {chr(65 + len(used_labels))}"

    cursor.execute(
        """
        INSERT INTO group_riders (
            group_id,
            rider_id,
            rider_label,
            rider_name,
            bike_name,
            lat,
            lon,
            fuel,
            fuel_range,
            mileage,
            speed,
            status
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
        (
            group_id,
            str(rider_id),
            assigned_label,
            rider_name,
            bike_name,
            lat,
            lon,
            fuel,
            fuel_range,
            mileage,
            speed,
            status
        )
    )

    conn.commit()

    cursor.execute(
        """
        SELECT *
        FROM group_riders
        WHERE group_id = %s AND rider_id = %s
        """,
        (
            group_id,
            str(rider_id)
        )
    )

    new_rider = cursor.fetchone()

    cursor.close()
    conn.close()

    return dict(new_rider), None


def create_demo_5_riders_convoy(
    code,
    center_lat,
    center_lon,
    leader_name="Rider A (You)",
    leader_phone="9876543210",
    leader_bike="Hero Splendor"
):
    code = code.strip().upper()

    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "SELECT * FROM group_rides WHERE code = %s",
        (code,)
    )

    ride = cursor.fetchone()

    if not ride:
        cursor.execute(
            """
            INSERT INTO group_rides (code, name, created_by)
            VALUES (%s, %s, %s)
            """,
            (
                code,
                "FuelWise 5-Rider Convoy",
                leader_phone
            )
        )

        conn.commit()

        cursor.execute(
            "SELECT * FROM group_rides WHERE code = %s",
            (code,)
        )

        ride = cursor.fetchone()

    group_id = ride["id"]

    # Clear previous riders for fresh demo
    cursor.execute(
        "DELETE FROM group_riders WHERE group_id = %s",
        (group_id,)
    )

    conn.commit()

    demo_riders = [
        {
            "rider_id": str(leader_phone),
            "label": "Rider A",
            "name": leader_name,
            "bike": leader_bike,
            "lat": round(center_lat, 6),
            "lon": round(center_lon, 6),
            "fuel": 2.5,
            "fuel_range": 150.0,
            "mileage": 60.0,
            "speed": 52.0,
            "status": "Cruising"
        },
        {
            "rider_id": "demo_rider_b",
            "label": "Rider B",
            "name": "Rider B (Karan)",
            "bike": "Honda Shine",
            "lat": round(center_lat + 0.0125, 6),
            "lon": round(center_lon + 0.0095, 6),
            "fuel": 4.2,
            "fuel_range": 231.0,
            "mileage": 55.0,
            "speed": 50.0,
            "status": "Cruising"
        },
        {
            "rider_id": "demo_rider_c",
            "label": "Rider C",
            "name": "Rider C (Amit)",
            "bike": "Bajaj Pulsar 150",
            "lat": round(center_lat + 0.0245, 6),
            "lon": round(center_lon + 0.0185, 6),
            "fuel": 0.85,
            "fuel_range": 36.5,
            "mileage": 43.0,
            "speed": 40.0,
            "status": "Low Fuel Warning"
        },
        {
            "rider_id": "demo_rider_d",
            "label": "Rider D",
            "name": "Rider D (Rohit)",
            "bike": "TVS Apache",
            "lat": round(center_lat - 0.0095, 6),
            "lon": round(center_lon - 0.0072, 6),
            "fuel": 3.1,
            "fuel_range": 124.0,
            "mileage": 40.0,
            "speed": 48.0,
            "status": "Cruising"
        },
        {
            "rider_id": "demo_rider_e",
            "label": "Rider E",
            "name": "Rider E (Sameer)",
            "bike": "Hero Splendor",
            "lat": round(center_lat + 0.0380, 6),
            "lon": round(center_lon + 0.0270, 6),
            "fuel": 1.6,
            "fuel_range": 96.0,
            "mileage": 60.0,
            "speed": 15.0,
            "status": "Refueling"
        }
    ]

    for r in demo_riders:
        cursor.execute(
            """
            INSERT INTO group_riders (
                group_id,
                rider_id,
                rider_label,
                rider_name,
                bike_name,
                lat,
                lon,
                fuel,
                fuel_range,
                mileage,
                speed,
                status
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                group_id,
                r["rider_id"],
                r["label"],
                r["name"],
                r["bike"],
                r["lat"],
                r["lon"],
                r["fuel"],
                r["fuel_range"],
                r["mileage"],
                r["speed"],
                r["status"]
            )
        )

    conn.commit()

    cursor.execute(
        """
        SELECT *
        FROM group_riders
        WHERE group_id = %s
        ORDER BY rider_label ASC
        """,
        (group_id,)
    )

    riders = cursor.fetchall()

    cursor.close()
    conn.close()

    return dict(ride), [dict(r) for r in riders]


def update_rider_telemetry(
    code,
    rider_id,
    lat,
    lon,
    fuel=None,
    speed=None,
    status=None,
    fuel_range=None,
    mileage=None
):
    code = code.strip().upper()

    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "SELECT id FROM group_rides WHERE code = %s",
        (code,)
    )

    ride = cursor.fetchone()

    if not ride:
        cursor.close()
        conn.close()

        return None

    group_id = ride["id"]

    cursor.execute(
        """
        SELECT *
        FROM group_riders
        WHERE group_id = %s AND rider_id = %s
        """,
        (
            group_id,
            str(rider_id)
        )
    )

    rider = cursor.fetchone()

    if not rider:
        cursor.close()
        conn.close()

        return None

    new_lat = float(lat) if lat is not None else rider["lat"]
    new_lon = float(lon) if lon is not None else rider["lon"]
    new_fuel = float(fuel) if fuel is not None else rider["fuel"]
    new_speed = float(speed) if speed is not None else rider["speed"]
    new_status = str(status) if status is not None else rider["status"]
    new_fuel_range = (
        float(fuel_range)
        if fuel_range is not None
        else rider["fuel_range"]
    )
    new_mileage = (
        float(mileage)
        if mileage is not None
        else rider["mileage"]
    )

    # Auto status update if fuel is critically low
    if new_fuel <= 1.0 and new_status not in ["Refueling", "Stopped"]:
        new_status = "Low Fuel Warning"

    cursor.execute(
        """
        UPDATE group_riders
        SET lat = %s,
            lon = %s,
            fuel = %s,
            speed = %s,
            status = %s,
            fuel_range = %s,
            mileage = %s,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = %s
        """,
        (
            new_lat,
            new_lon,
            new_fuel,
            new_speed,
            new_status,
            new_fuel_range,
            new_mileage,
            rider["id"]
        )
    )

    conn.commit()

    cursor.execute(
        "SELECT * FROM group_riders WHERE id = %s",
        (rider["id"],)
    )

    updated = cursor.fetchone()

    cursor.close()
    conn.close()

    return dict(updated)


def get_group_ride_state(code):
    code = code.strip().upper()

    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "SELECT * FROM group_rides WHERE code = %s",
        (code,)
    )

    ride = cursor.fetchone()

    if not ride:
        cursor.close()
        conn.close()

        return None

    cursor.execute(
        """
        SELECT *
        FROM group_riders
        WHERE group_id = %s
        ORDER BY rider_label ASC
        """,
        (ride["id"],)
    )

    riders = cursor.fetchall()

    cursor.close()
    conn.close()

    return {
        "ride": dict(ride),
        "riders": [dict(r) for r in riders]
    }


def leave_group_ride(code, rider_id):
    code = code.strip().upper()

    conn = get_db_connection()
    cursor = conn.cursor()

    cursor.execute(
        "SELECT id FROM group_rides WHERE code = %s",
        (code,)
    )

    ride = cursor.fetchone()

    if ride:
        cursor.execute(
            """
            DELETE FROM group_riders
            WHERE group_id = %s AND rider_id = %s
            """,
            (
                ride["id"],
                str(rider_id)
            )
        )

        conn.commit()

    cursor.close()
    conn.close()

    return True


if __name__ == "__main__":
    init_db()
    print("PostgreSQL database initialized successfully.")